version: "3"
services:
  cert-monitor:
    build: .
    environment:
      - GOTIFY_URL=url
      - GOTIFY_TOKEN=token
      - ALERT_NOTICE=14 7 5 3 2 1
    ports:
      - "3000:8080"
    volumes:
      - "./server/certs:/usr/src/app"
